[package]
name = "leo-status-driver"
version = "2.0.3"
edition = "2021"

[dependencies]
thiserror = "2.0.17"
hidapi = { version = "2.6.3", optional = true }

[lib]

[features]
default = ["hidapi"]
hidapi = ["dep:hidapi"]
